- name: Pruebas con flow control
  hosts: all
  vars:
    db_package: mariadb-server
    db_service: mariadb
    db_users:
      - db_admin
      - db_user
    configure_database_path: /etc/my.cnf
  tasks:
    - name: crear una lista de usuarios SI el host pertenece al grupo de BBDD
      user:
        name: "{{item}}"
      with_items: "{{db_users}}"
      when: inventory_hostname in groups["database"]
    - name: instala servidor de BBDD SI la variable existe
      yum:
        name: "{{db_package}}"
      when: db_package is defined and inventory_hostname in groups["database"]
    - name: configurar la BBDD si está definida la variable que contiene la confi y es del grupo de BBDD
      vars:
        extra_packages:
          - mariadb-bench
          - mariadb-libs
          - mariadb-test
      include: flow-control-configurar-bbdd-TaskFile.yml
      when: configure_database_path is defined and inventory_hostname in groups["database"] and db_service is defined
