---
# Primer ejemplo de pruebas con Playbooks
- name: Disponibilizar servicio WEB
  hosts: centos
  tasks:
    - name: Instalar Servicio para WEB - httpd
      yum:
        name: httpd
        state: latest
    - name: Instalar Servicio para Firewall - firewalld
      yum:
        name: firewalld
        state: latest

    - name: Habilitar el servicio de firewalld en arranque y levantarlo
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Permitir en el firewall el acceso al servicio httpd 
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: Habilitar el servicio httpd en arranque y levantarlo
      service: 
        name: httpd
        enabled: true
        state: started
    - name: Personlizar pagina de inicio
      copy:
        content: "Bienvenido a mi pagina WEB"
        dest: /var/www/html/index.html
- name: Probar la pagina WEB
  hosts: localhost
  tasks:
    - name: Invocar la pagina WEB
      uri:
        url: http://nodo1
        status_code: 200 
