---
# Primer ejemplo de pruebas con Playbooks
- name: Cambiar la pagina de login
  hosts: all
  tasks:
  - template:
      src: /home/ansible/ansible-containers-lab/templates/motd-utf8.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
